name: CI to Container Registry
on:
  push:
    branches: [main]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registrey: krist00fer.azurecr.io
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: krist00fer/whisper:latest
          
      - name: Image digest
        run: echo @{{ steps.docker_build.outputs.digest }}
