name: CI to Container Registry
on:
  push:
    branches: [main]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: krist00fer.azurecr.io
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: Test
        run: echo "Kristofer was here"
    
          
      - name: Image digest
        run: echo @{{ steps.docker_build.outputs.digest }}
